import {
  Product,
  Category,
  StockMovement,
  Order,
  Payment,
  ServiceItem,
  ServiceBooking,
  Vehicle,
  Customer,
  Mechanic,
  User,
  RolePermissions,
  CMSPage,
  Article,
  Banner,
  GalleryItem,
  Testimonial,
  FAQ,
  MediaFile,
  WorkshopSettings,
} from 'types/workshop';

export const initialCategories: Category[] = [
  {
    id: 'cat-oli',
    name: 'Oli & Pelumas Mesin',
    slug: 'oli-pelumas',
    description: 'Oli mesin 4T, oli gardan matic, minyak rem, dan radiator coolant.',
    itemCount: 14,
    type: 'PRODUCT',
  },
  {
    id: 'cat-cvt',
    name: 'Sparepart CVT Matic',
    slug: 'sparepart-cvt',
    description: 'Roller racing, v-belt, per cvt, mangkok ganda, kampas ganda.',
    itemCount: 22,
    type: 'PRODUCT',
  },
  {
    id: 'cat-pengereman',
    name: 'Sistem Pengereman',
    slug: 'sistem-pengereman',
    description: 'Kampas rem ceramic/organik, piringan cakram floating, kaliper, selang rem braided.',
    itemCount: 18,
    type: 'PRODUCT',
  },
  {
    id: 'cat-mesin',
    name: 'Mesin & Performa (Tune Up)',
    slug: 'mesin-performa',
    description: 'Busi iridium, ECU racing, injector racing, noken as, piston kit.',
    itemCount: 29,
    type: 'PRODUCT',
  },
  {
    id: 'cat-kaki',
    name: 'Suspensi & Kaki-kaki',
    slug: 'suspensi-kaki-kaki',
    description: 'Shockbreaker tabung, bearing roda, velg, as roda.',
    itemCount: 12,
    type: 'PRODUCT',
  },
  {
    id: 'cat-kelistrikan',
    name: 'Kelistrikan & Aki',
    slug: 'kelistrikan-aki',
    description: 'Aki kering gel, lampu biled projector, relay, klakson denso.',
    itemCount: 15,
    type: 'PRODUCT',
  },
  // Service categories
  {
    id: 'cat-srv-reguler',
    name: 'Service Berkala & Reguler',
    slug: 'service-reguler',
    description: 'Tune up harian, ganti oli, pengecekan kelayakan jalan.',
    itemCount: 4,
    type: 'SERVICE',
  },
  {
    id: 'cat-srv-cvt',
    name: 'Service Spesialis CVT Matic',
    slug: 'service-cvt',
    description: 'Bongkar bersih CVT, greasing high-temp, custom bubut pulley.',
    itemCount: 3,
    type: 'SERVICE',
  },
  {
    id: 'cat-srv-mesin',
    name: 'Overhaul & Heavy Repair',
    slug: 'overhaul-mesin',
    description: 'Turun mesin, skir klep, porting polish, ganti kruk as.',
    itemCount: 5,
    type: 'SERVICE',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-001',
    name: 'Motul 7100 4T 10W-40 100% Synthetic (1L)',
    sku: 'MOT-7100-10W40',
    category: 'Oli & Pelumas Mesin',
    categoryId: 'cat-oli',
    description: 'Oli ester fully synthetic untuk performa mesin maksimal, meredam panas dan suara mesin.',
    price: 195000,
    discountPrice: 185000,
    stock: 28,
    minStock: 10,
    weightGram: 1000,
    images: ['https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: true,
    compatibleVehicles: ['Honda Vario 160', 'Honda PCX 160', 'Yamaha NMAX 155', 'Yamaha Aerox 155', 'Kawasaki ZX25R'],
    brand: 'Motul',
    rating: 4.9,
    salesCount: 142,
    updatedAt: '2026-08-24 14:30',
  },
  {
    id: 'prod-002',
    name: 'Daytona Ultra Drive CVT Roller Set (10g - 13g)',
    sku: 'DAY-CVT-ROL-11G',
    category: 'Sparepart CVT Matic',
    categoryId: 'cat-cvt',
    description: 'Roller Daytona bahan teflon self-lubricating, tahan gesekan tinggi dan tidak mudah peyang.',
    price: 110000,
    discountPrice: 95000,
    stock: 45,
    minStock: 15,
    weightGram: 150,
    images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: true,
    compatibleVehicles: ['Honda Vario 125/150/160', 'Honda Beat ESP', 'Honda Scoopy FI'],
    brand: 'Daytona',
    rating: 4.8,
    salesCount: 215,
    updatedAt: '2026-08-23 10:15',
  },
  {
    id: 'prod-003',
    name: 'Bendix Brake Pad Ceramic General CT (Front)',
    sku: 'BDX-BP-HON-V160',
    category: 'Sistem Pengereman',
    categoryId: 'cat-pengereman',
    description: 'Kampas rem ceramic Bendix teknologi Stealth, pengereman pakem tanpa bunyi berdecit.',
    price: 85000,
    stock: 6, // LOW STOCK
    minStock: 12,
    weightGram: 250,
    images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: false,
    compatibleVehicles: ['Honda Vario 160 ABS/CBS', 'Honda PCX 150/160', 'Honda ADV 150/160'],
    brand: 'Bendix',
    rating: 4.7,
    salesCount: 89,
    updatedAt: '2026-08-25 08:20',
  },
  {
    id: 'prod-004',
    name: 'TDR Racing Stainless Braided Brake Hose (90cm)',
    sku: 'TDR-BH-90-RED',
    category: 'Sistem Pengereman',
    categoryId: 'cat-pengereman',
    description: 'Selang rem serat baja anti gembung, tekanan hidrolik rem lebih responsif dan tahan panas.',
    price: 165000,
    stock: 14,
    minStock: 8,
    weightGram: 300,
    images: ['https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: false,
    compatibleVehicles: ['Yamaha NMAX 155', 'Yamaha Aerox 155', 'Honda Vario 160'],
    brand: 'TDR Racing',
    rating: 4.9,
    salesCount: 78,
    updatedAt: '2026-08-22 16:40',
  },
  {
    id: 'prod-005',
    name: 'NGK Laser Iridium Spark Plug CPR8EAIX-9',
    sku: 'NGK-IRID-CPR8',
    category: 'Mesin & Performa (Tune Up)',
    categoryId: 'cat-mesin',
    description: 'Busi iridium laser ujung elektroda 0.6mm, pembakaran presisi, start instan & hemat bahan bakar.',
    price: 135000,
    discountPrice: 125000,
    stock: 3, // CRITICAL LOW STOCK
    minStock: 15,
    weightGram: 80,
    images: ['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: true,
    compatibleVehicles: ['Honda Beat FI', 'Honda Vario 125/150/160', 'Yamaha NMAX 155', 'Yamaha Jupiter MX'],
    brand: 'NGK',
    rating: 5.0,
    salesCount: 310,
    updatedAt: '2026-08-25 06:10',
  },
  {
    id: 'prod-006',
    name: 'RCB Rear Shock Absorber VS Series Black Edition (330mm)',
    sku: 'RCB-SHK-VS-330',
    category: 'Suspensi & Kaki-kaki',
    categoryId: 'cat-kaki',
    description: 'Shockbreaker tabung pisah dengan setelan preload, compression & rebound damping.',
    price: 2450000,
    discountPrice: 2300000,
    stock: 5,
    minStock: 4,
    weightGram: 3800,
    images: ['https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: true,
    compatibleVehicles: ['Honda Vario 125/150/160', 'Yamaha Aerox 155', 'Honda Beat'],
    brand: 'RCB (Racing Boy)',
    rating: 4.9,
    salesCount: 34,
    updatedAt: '2026-08-20 11:00',
  },
  {
    id: 'prod-007',
    name: 'Yuasa Maintenance Free YTZ6V (12V 5Ah)',
    sku: 'YUA-MF-YTZ6V',
    category: 'Kelistrikan & Aki',
    categoryId: 'cat-kelistrikan',
    description: 'Aki motor siap pakai bebas perawatan dengan ampere stabil dan CCA tinggi untuk starter elektrik.',
    price: 295000,
    stock: 0, // OUT OF STOCK
    minStock: 6,
    weightGram: 2100,
    images: ['https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=500&auto=format&fit=crop&q=80'],
    status: 'ACTIVE',
    featured: false,
    compatibleVehicles: ['Honda PCX 150/160', 'Honda Vario 150/160', 'Yamaha NMAX 155', 'Honda CBR 150R'],
    brand: 'Yuasa',
    rating: 4.8,
    salesCount: 65,
    updatedAt: '2026-08-24 18:00',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'sm-001',
    productId: 'prod-001',
    productName: 'Motul 7100 4T 10W-40 100% Synthetic (1L)',
    sku: 'MOT-7100-10W40',
    type: 'RESTOCK',
    quantity: 24,
    previousStock: 4,
    newStock: 28,
    reason: 'Penerimaan PO Supplier PT Motul Indonesia #PO-8831',
    userName: 'Budi Santoso',
    userRole: 'Inventory Manager',
    date: '2026-08-24 14:30',
  },
  {
    id: 'sm-002',
    productId: 'prod-005',
    productName: 'NGK Laser Iridium Spark Plug CPR8EAIX-9',
    sku: 'NGK-IRID-CPR8',
    type: 'SALE',
    quantity: -2,
    previousStock: 5,
    newStock: 3,
    reason: 'Penjualan Online Order #ORD-20260825-001',
    userName: 'Sistem Kasir',
    userRole: 'System',
    date: '2026-08-25 06:10',
  },
  {
    id: 'sm-003',
    productId: 'prod-003',
    productName: 'Bendix Brake Pad Ceramic General CT (Front)',
    sku: 'BDX-BP-HON-V160',
    type: 'DAMAGE',
    quantity: -1,
    previousStock: 7,
    newStock: 6,
    reason: 'Kemasan rusak basah saat pemindahan rak gudang',
    userName: 'Rian Pratama',
    userRole: 'Staff Gudang',
    date: '2026-08-25 08:20',
  },
  {
    id: 'sm-004',
    productId: 'prod-007',
    productName: 'Yuasa Maintenance Free YTZ6V (12V 5Ah)',
    sku: 'YUA-MF-YTZ6V',
    type: 'SALE',
    quantity: -3,
    previousStock: 3,
    newStock: 0,
    reason: 'Instalasi Service Booking #SB-202608-004',
    userName: 'Agus Mekanik',
    userRole: 'Head Mechanic',
    date: '2026-08-24 18:00',
  },
];

export const initialServices: ServiceItem[] = [
  {
    id: 'srv-001',
    name: 'Paket Service CVT Komplit + Greasing High-Temp',
    slug: 'service-cvt-komplit',
    category: 'Service Spesialis CVT Matic',
    description: 'Pembersihan ruang CVT total, pembersihan kampas ganda & mangkok, pengecekan v-belt & roller, serta pelumasan grease high-temperature.',
    price: 85000,
    estimatedDuration: '45 Menit',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=500&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    featured: true,
  },
  {
    id: 'srv-002',
    name: 'Tune Up Injeksi & Gurah Mesin (Carbon Cleaner)',
    slug: 'tune-up-injeksi-carbon-cleaner',
    category: 'Service Berkala & Reguler',
    description: 'Pembersihan throttle body, kalibrasi injector ultrasonic, pembersihan ruang bakar dari kerak karbon, dan reset ECU scanner.',
    price: 135000,
    estimatedDuration: '60 Menit',
    image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    featured: true,
  },
  {
    id: 'srv-003',
    name: 'Service Ganti Oli Mesin + Oli Gardan + Cek 15 Titik Keselamatan',
    slug: 'ganti-oli-cek-15-titik',
    category: 'Service Berkala & Reguler',
    description: 'Jasa penggantian oli mesin & gardan, pengecekan tekanan angin ban, kondisi kampas rem, tegangan aki, dan kelistrikan.',
    price: 35000,
    estimatedDuration: '20 Menit',
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=500&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    featured: true,
  },
  {
    id: 'srv-004',
    name: 'Overhaul Mesin (Turun Mesin Total & Skir Klep)',
    slug: 'overhaul-mesin-total',
    category: 'Overhaul & Heavy Repair',
    description: 'Bongkar mesin total untuk mengatasi ngebul/kehabisan oli, ganti ring piston, korter silinder, ganti sil klep, dan skir klep presisi.',
    price: 650000,
    estimatedDuration: '1 - 2 Hari',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    featured: false,
  },
  {
    id: 'srv-005',
    name: 'Dyno Tuning & Pemetaan ECU Jup/BRT/Aracer',
    slug: 'dyno-tuning-ecu',
    category: 'Overhaul & Heavy Repair',
    description: 'Uji performa dynometer roda belakang, kalibrasi rasio bahan bakar (AFR), dan setting timing pengapian untuk performa puncak.',
    price: 450000,
    estimatedDuration: '90 Menit',
    image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=500&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    featured: true,
  },
];

export const initialMechanics: Mechanic[] = [
  {
    id: 'mech-001',
    name: 'Agus "Bogel" Setiawan',
    phone: '0812-9876-5432',
    specialization: 'CVT Specialist & Matic Tuning',
    status: 'BUSY',
    activeBookingsCount: 2,
    rating: 4.95,
  },
  {
    id: 'mech-002',
    name: 'Fajar Kurniawan',
    phone: '0821-4567-8901',
    specialization: 'Injeksi, ECU Tuning & Kelistrikan',
    status: 'AVAILABLE',
    activeBookingsCount: 0,
    rating: 4.88,
  },
  {
    id: 'mech-003',
    name: 'Doni Prasetyo',
    phone: '0857-1234-5678',
    specialization: 'Engine Overhaul & Porting Polish',
    status: 'BUSY',
    activeBookingsCount: 1,
    rating: 4.92,
  },
  {
    id: 'mech-004',
    name: 'Rian Hidayat',
    phone: '0878-3344-5566',
    specialization: 'Suspensi, Rem & Fast Moving Parts',
    status: 'AVAILABLE',
    activeBookingsCount: 0,
    rating: 4.80,
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: 'veh-001',
    customerId: 'cust-001',
    customerName: 'Dimas Anggara',
    customerPhone: '0812-8899-7711',
    brand: 'Honda',
    model: 'Vario 160 ABS',
    year: 2024,
    licensePlate: 'N 1234 XX',
    engineType: '160cc eSP+ 4-Katup PGM-FI',
    odometerKm: 8450,
    color: 'Matte Grande Black',
    notes: 'Kerap perjalanan jarak jauh Malang-Surabaya.',
    createdAt: '2026-01-15',
  },
  {
    id: 'veh-002',
    customerId: 'cust-002',
    customerName: 'Siti Rahmawati',
    customerPhone: '0813-2233-4455',
    brand: 'Yamaha',
    model: 'NMAX 155 Connected',
    year: 2023,
    licensePlate: 'B 4567 ABC',
    engineType: '155cc BlueCore VVA Injeksi',
    odometerKm: 16200,
    color: 'Matte Blue',
    notes: 'Ada getaran halus di tarikan awal CVT.',
    createdAt: '2026-02-10',
  },
  {
    id: 'veh-003',
    customerId: 'cust-003',
    customerName: 'Bambang Wijaya',
    customerPhone: '0819-7788-9900',
    brand: 'Kawasaki',
    model: 'Ninja ZX-25R ABS SE',
    year: 2023,
    licensePlate: 'D 3321 ZZZ',
    engineType: '249.8cc In-Line Four DOHC',
    odometerKm: 6100,
    color: 'Lime Green / Ebony',
    notes: 'Rutin service ganti oli Motul 7100 dan cek filter oli.',
    createdAt: '2026-03-05',
  },
  {
    id: 'veh-004',
    customerId: 'cust-004',
    customerName: 'Reza Fahlevi',
    customerPhone: '0852-6677-8899',
    brand: 'Honda',
    model: 'Beat Street CBS',
    year: 2022,
    licensePlate: 'N 5912 KL',
    engineType: '110cc eSP SOHC',
    odometerKm: 28500,
    color: 'Street Silver',
    notes: 'Motor operasional harian.',
    createdAt: '2026-04-18',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-001',
    name: 'Dimas Anggara',
    phone: '0812-8899-7711',
    email: 'dimas.anggara@gmail.com',
    totalOrders: 4,
    totalSpending: 2350000,
    lastOrderDate: '2026-08-25',
    lastBookingDate: '2026-08-25',
    vehicles: [initialVehicles[0]],
    address: {
      street: 'Jl. Ijen No. 45',
      city: 'Kota Malang',
      province: 'Jawa Timur',
      postalCode: '65115',
    },
    createdAt: '2026-01-15',
  },
  {
    id: 'cust-002',
    name: 'Siti Rahmawati',
    phone: '0813-2233-4455',
    email: 'siti.rahma@yahoo.com',
    totalOrders: 2,
    totalSpending: 890000,
    lastOrderDate: '2026-08-20',
    lastBookingDate: '2026-08-25',
    vehicles: [initialVehicles[1]],
    address: {
      street: 'Jl. Margonda Raya No. 12',
      city: 'Depok',
      province: 'Jawa Barat',
      postalCode: '16424',
    },
    createdAt: '2026-02-10',
  },
  {
    id: 'cust-003',
    name: 'Bambang Wijaya',
    phone: '0819-7788-9900',
    email: 'bambang.w@corp.co.id',
    totalOrders: 6,
    totalSpending: 6750000,
    lastOrderDate: '2026-08-18',
    lastBookingDate: '2026-08-22',
    vehicles: [initialVehicles[2]],
    address: {
      street: 'Jl. R.E. Martadinata No. 88',
      city: 'Bandung',
      province: 'Jawa Barat',
      postalCode: '40115',
    },
    createdAt: '2026-03-05',
  },
  {
    id: 'cust-004',
    name: 'Reza Fahlevi',
    phone: '0852-6677-8899',
    email: 'reza.fahlevi@gmail.com',
    totalOrders: 1,
    totalSpending: 220000,
    lastOrderDate: '2026-08-10',
    lastBookingDate: '2026-08-24',
    vehicles: [initialVehicles[3]],
    address: {
      street: 'Jl. Soekarno Hatta No. 20',
      city: 'Kota Malang',
      province: 'Jawa Timur',
      postalCode: '65141',
    },
    createdAt: '2026-04-18',
  },
];

export const initialBookings: ServiceBooking[] = [
  {
    id: 'sb-001',
    bookingNumber: 'SB-202608-001',
    customerId: 'cust-001',
    customerName: 'Dimas Anggara',
    customerPhone: '0812-8899-7711',
    vehicleId: 'veh-001',
    vehicleModel: 'Honda Vario 160 ABS',
    vehiclePlate: 'N 1234 XX',
    vehicleYear: 2024,
    serviceId: 'srv-001',
    serviceName: 'Paket Service CVT Komplit + Greasing High-Temp',
    mechanicId: 'mech-001',
    mechanicName: 'Agus "Bogel" Setiawan',
    date: '2026-08-25',
    time: '09:00 WIB',
    status: 'IN_SERVICE',
    notes: 'Tolong cek roller sekalian ganti roller Daytona 11g.',
    estimatedCost: 195000,
    createdAt: '2026-08-24 16:20',
  },
  {
    id: 'sb-002',
    bookingNumber: 'SB-202608-002',
    customerId: 'cust-002',
    customerName: 'Siti Rahmawati',
    customerPhone: '0813-2233-4455',
    vehicleId: 'veh-002',
    vehicleModel: 'Yamaha NMAX 155 Connected',
    vehiclePlate: 'B 4567 ABC',
    vehicleYear: 2023,
    serviceId: 'srv-002',
    serviceName: 'Tune Up Injeksi & Gurah Mesin (Carbon Cleaner)',
    mechanicId: 'mech-002',
    mechanicName: 'Fajar Kurniawan',
    date: '2026-08-25',
    time: '11:00 WIB',
    status: 'CONFIRMED',
    notes: 'Motor sering brebet saat akselerasi awal di lampu merah.',
    estimatedCost: 135000,
    createdAt: '2026-08-24 19:45',
  },
  {
    id: 'sb-003',
    bookingNumber: 'SB-202608-003',
    customerId: 'cust-003',
    customerName: 'Bambang Wijaya',
    customerPhone: '0819-7788-9900',
    vehicleId: 'veh-003',
    vehicleModel: 'Kawasaki Ninja ZX-25R ABS SE',
    vehiclePlate: 'D 3321 ZZZ',
    vehicleYear: 2023,
    serviceId: 'srv-005',
    serviceName: 'Dyno Tuning & Pemetaan ECU Jup/BRT/Aracer',
    mechanicId: 'mech-003',
    mechanicName: 'Doni Prasetyo',
    date: '2026-08-25',
    time: '14:00 WIB',
    status: 'CONFIRMED',
    notes: 'Baru ganti knalpot full system header titanium, minta setting AFR 13.2.',
    estimatedCost: 645000,
    createdAt: '2026-08-24 11:10',
  },
  {
    id: 'sb-004',
    bookingNumber: 'SB-202608-004',
    customerId: 'cust-004',
    customerName: 'Reza Fahlevi',
    customerPhone: '0852-6677-8899',
    vehicleId: 'veh-004',
    vehicleModel: 'Honda Beat Street CBS',
    vehiclePlate: 'N 5912 KL',
    vehicleYear: 2022,
    serviceId: 'srv-003',
    serviceName: 'Service Ganti Oli Mesin + Oli Gardan + Cek 15 Titik Keselamatan',
    mechanicId: 'mech-001',
    mechanicName: 'Agus "Bogel" Setiawan',
    date: '2026-08-25',
    time: '15:30 WIB',
    status: 'PENDING',
    notes: 'Booking lewat web, minta dikabari kalau antrian kosong.',
    estimatedCost: 110000,
    createdAt: '2026-08-25 07:15',
  },
  {
    id: 'sb-005',
    bookingNumber: 'SB-202608-005',
    customerId: 'cust-001',
    customerName: 'Dimas Anggara',
    customerPhone: '0812-8899-7711',
    vehicleId: 'veh-001',
    vehicleModel: 'Honda Vario 160 ABS',
    vehiclePlate: 'N 1234 XX',
    vehicleYear: 2024,
    serviceId: 'srv-003',
    serviceName: 'Service Ganti Oli Mesin + Oli Gardan',
    mechanicId: 'mech-004',
    mechanicName: 'Rian Hidayat',
    date: '2026-08-10',
    time: '10:00 WIB',
    status: 'COMPLETED',
    notes: 'Pengerjaan selesai tepat waktu.',
    estimatedCost: 220000,
    createdAt: '2026-08-09 14:00',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'ORD-20260825-001',
    customerId: 'cust-001',
    customerName: 'Dimas Anggara',
    customerEmail: 'dimas.anggara@gmail.com',
    customerPhone: '0812-8899-7711',
    items: [
      {
        productId: 'prod-001',
        productName: 'Motul 7100 4T 10W-40 100% Synthetic (1L)',
        sku: 'MOT-7100-10W40',
        price: 185000,
        quantity: 2,
        image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=500&auto=format&fit=crop&q=80',
      },
      {
        productId: 'prod-005',
        productName: 'NGK Laser Iridium Spark Plug CPR8EAIX-9',
        sku: 'NGK-IRID-CPR8',
        price: 125000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=500&auto=format&fit=crop&q=80',
      },
    ],
    subtotal: 495000,
    shippingFee: 20000,
    discount: 25000,
    total: 490000,
    shippingAddress: {
      recipientName: 'Dimas Anggara',
      phone: '0812-8899-7711',
      street: 'Jl. Ijen No. 45',
      city: 'Kota Malang',
      province: 'Jawa Timur',
      postalCode: '65115',
      courier: 'J&T Express Reguler',
      trackingNumber: 'JT88192039120',
    },
    paymentMethod: 'QRIS',
    paymentStatus: 'PAID',
    orderStatus: 'PROCESSING',
    timeline: [
      {
        status: 'Order Placed',
        timestamp: '2026-08-25 06:10',
        description: 'Customer menyelesaikan checkout via Web Store.',
      },
      {
        status: 'Payment Verified',
        timestamp: '2026-08-25 06:15',
        description: 'Pembayaran QRIS Rp 490.000 terverifikasi otomatis.',
      },
      {
        status: 'Processing',
        timestamp: '2026-08-25 07:30',
        description: 'Pesanan sedang disiapkan di gudang sparepart.',
      },
    ],
    createdAt: '2026-08-25 06:10',
    updatedAt: '2026-08-25 07:30',
  },
  {
    id: 'ord-002',
    orderNumber: 'ORD-20260825-002',
    customerId: 'cust-002',
    customerName: 'Siti Rahmawati',
    customerEmail: 'siti.rahma@yahoo.com',
    customerPhone: '0813-2233-4455',
    items: [
      {
        productId: 'prod-002',
        productName: 'Daytona Ultra Drive CVT Roller Set (11g)',
        sku: 'DAY-CVT-ROL-11G',
        price: 95000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
      },
      {
        productId: 'prod-004',
        productName: 'TDR Racing Stainless Braided Brake Hose (90cm)',
        sku: 'TDR-BH-90-RED',
        price: 165000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500&auto=format&fit=crop&q=80',
      },
    ],
    subtotal: 260000,
    shippingFee: 15000,
    discount: 0,
    total: 275000,
    shippingAddress: {
      recipientName: 'Siti Rahmawati',
      phone: '0813-2233-4455',
      street: 'Jl. Margonda Raya No. 12',
      city: 'Depok',
      province: 'Jawa Barat',
      postalCode: '16424',
      courier: 'SiCepat BEST',
    },
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'WAITING_VERIFICATION',
    orderStatus: 'WAITING_PAYMENT',
    paymentProof: {
      imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
      accountHolder: 'Siti Rahmawati',
      bankName: 'BCA (Bank Central Asia)',
      transferDate: '2026-08-25 07:05',
      notes: 'Sudah transfer Rp 275.000 dari rekening m-BCA a.n Siti Rahmawati.',
    },
    timeline: [
      {
        status: 'Order Placed',
        timestamp: '2026-08-25 06:50',
        description: 'Customer checkout memilih metode Transfer Bank BCA.',
      },
      {
        status: 'Payment Proof Uploaded',
        timestamp: '2026-08-25 07:08',
        description: 'Customer mengunggah bukti transfer manual Rp 275.000.',
      },
    ],
    createdAt: '2026-08-25 06:50',
    updatedAt: '2026-08-25 07:08',
  },
  {
    id: 'ord-003',
    orderNumber: 'ORD-20260824-008',
    customerId: 'cust-003',
    customerName: 'Bambang Wijaya',
    customerEmail: 'bambang.w@corp.co.id',
    customerPhone: '0819-7788-9900',
    items: [
      {
        productId: 'prod-006',
        productName: 'RCB Rear Shock Absorber VS Series Black Edition (330mm)',
        sku: 'RCB-SHK-VS-330',
        price: 2300000,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=500&auto=format&fit=crop&q=80',
      },
    ],
    subtotal: 2300000,
    shippingFee: 45000,
    discount: 100000,
    total: 2245000,
    shippingAddress: {
      recipientName: 'Bambang Wijaya',
      phone: '0819-7788-9900',
      street: 'Jl. R.E. Martadinata No. 88',
      city: 'Bandung',
      province: 'Jawa Barat',
      postalCode: '40115',
      courier: 'JNE Trucking (JTR)',
      trackingNumber: 'JNE99182310293',
    },
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'PAID',
    orderStatus: 'SHIPPED',
    paymentProof: {
      imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
      accountHolder: 'Bambang Wijaya',
      bankName: 'Mandiri',
      transferDate: '2026-08-24 10:30',
    },
    timeline: [
      {
        status: 'Order Placed',
        timestamp: '2026-08-24 10:15',
        description: 'Checkout pesanan online.',
      },
      {
        status: 'Payment Approved',
        timestamp: '2026-08-24 10:45',
        description: 'Admin Finance memverifikasi transfer Mandiri Rp 2.245.000.',
      },
      {
        status: 'Shipped',
        timestamp: '2026-08-24 16:00',
        description: 'Paket diserahkan ke kurir JNE Trucking.',
      },
    ],
    createdAt: '2026-08-24 10:15',
    updatedAt: '2026-08-24 16:00',
  },
];

export const initialPayments: Payment[] = [
  {
    id: 'pay-001',
    orderId: 'ord-002',
    orderNumber: 'ORD-20260825-002',
    customerName: 'Siti Rahmawati',
    amount: 275000,
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'WAITING_VERIFICATION',
    bankDestination: 'BCA 1234567890 an Bengkel JTM Tech',
    paymentProof: {
      imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
      accountHolder: 'Siti Rahmawati',
      bankName: 'BCA (Bank Central Asia)',
      transferDate: '2026-08-25 07:05',
      notes: 'Transfer nominal pas Rp 275.000 via BCA Mobile.',
    },
    createdAt: '2026-08-25 07:08',
  },
  {
    id: 'pay-002',
    orderId: 'ord-001',
    orderNumber: 'ORD-20260825-001',
    customerName: 'Dimas Anggara',
    amount: 490000,
    paymentMethod: 'QRIS',
    paymentStatus: 'PAID',
    qrisRef: 'NMID-93821039-QRIS',
    verifiedBy: 'Auto-Gateway',
    verifiedAt: '2026-08-25 06:15',
    createdAt: '2026-08-25 06:10',
  },
  {
    id: 'pay-003',
    orderId: 'ord-003',
    orderNumber: 'ORD-20260824-008',
    customerName: 'Bambang Wijaya',
    amount: 2245000,
    paymentMethod: 'BANK_TRANSFER',
    paymentStatus: 'PAID',
    bankDestination: 'Mandiri 1400019283741 an Bengkel JTM Tech',
    paymentProof: {
      imageUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
      accountHolder: 'Bambang Wijaya',
      bankName: 'Bank Mandiri',
      transferDate: '2026-08-24 10:30',
    },
    verifiedBy: 'Ahmad Fauzi (Admin)',
    verifiedAt: '2026-08-24 10:45',
    createdAt: '2026-08-24 10:15',
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-001',
    name: 'Ahmad Fauzi',
    email: 'fauzi@jtmtech.id',
    phone: '0811-2233-4455',
    role: 'OWNER',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    lastLogin: '2026-08-25 07:15',
    createdAt: '2025-01-01',
  },
  {
    id: 'usr-002',
    name: 'Rina Marlina',
    email: 'rina.admin@jtmtech.id',
    phone: '0812-7766-5544',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    lastLogin: '2026-08-25 07:00',
    createdAt: '2025-02-15',
  },
  {
    id: 'usr-003',
    name: 'Bayu Saputra',
    email: 'bayu.kasir@jtmtech.id',
    phone: '0857-4455-6677',
    role: 'CASHIER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    lastLogin: '2026-08-24 17:30',
    createdAt: '2025-05-10',
  },
  {
    id: 'usr-004',
    name: 'Agus Setiawan',
    email: 'agus.mechanic@jtmtech.id',
    phone: '0812-9876-5432',
    role: 'MECHANIC',
    status: 'ACTIVE',
    lastLogin: '2026-08-25 08:00',
    createdAt: '2025-03-01',
  },
  {
    id: 'usr-005',
    name: 'Nadia Putri',
    email: 'nadia.content@jtmtech.id',
    phone: '0813-9988-7766',
    role: 'CONTENT_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    lastLogin: '2026-08-24 15:40',
    createdAt: '2025-06-01',
  },
];

export const initialRoles: RolePermissions[] = [
  {
    role: 'OWNER',
    description: 'Akses penuh tanpa batas ke semua modul workshop, transaksi, settings, dan keuangan.',
    permissions: {
      products: { view: true, create: true, update: true, delete: true },
      orders: { view: true, create: true, update: true, delete: true },
      inventory: { view: true, create: true, update: true, delete: true },
      bookings: { view: true, create: true, update: true, delete: true },
      customers: { view: true, create: true, update: true, delete: true },
      payments: { view: true, create: true, update: true, delete: true },
      cms: { view: true, create: true, update: true, delete: true },
      users: { view: true, create: true, update: true, delete: true },
      settings: { view: true, create: true, update: true, delete: true },
    },
  },
  {
    role: 'ADMIN',
    description: 'Mengelola operasional harian, verifikasi pembayaran, stok produk, booking bengkel, dan customer.',
    permissions: {
      products: { view: true, create: true, update: true, delete: true },
      orders: { view: true, create: true, update: true, delete: false },
      inventory: { view: true, create: true, update: true, delete: false },
      bookings: { view: true, create: true, update: true, delete: true },
      customers: { view: true, create: true, update: true, delete: false },
      payments: { view: true, create: true, update: true, delete: false },
      cms: { view: true, create: true, update: true, delete: true },
      users: { view: true, create: true, update: true, delete: false },
      settings: { view: true, create: false, update: true, delete: false },
    },
  },
  {
    role: 'CASHIER',
    description: 'Membuat transaksi POS / Order, menerima pembayaran tunai/QRIS, dan melihat katalog barang.',
    permissions: {
      products: { view: true, create: false, update: false, delete: false },
      orders: { view: true, create: true, update: true, delete: false },
      inventory: { view: true, create: false, update: false, delete: false },
      bookings: { view: true, create: true, update: true, delete: false },
      customers: { view: true, create: true, update: true, delete: false },
      payments: { view: true, create: true, update: true, delete: false },
      cms: { view: false, create: false, update: false, delete: false },
      users: { view: false, create: false, update: false, delete: false },
      settings: { view: false, create: false, update: false, delete: false },
    },
  },
  {
    role: 'MECHANIC',
    description: 'Melihat antrian service motor, update progress pengerjaan service, dan checklist inspeksi.',
    permissions: {
      products: { view: true, create: false, update: false, delete: false },
      orders: { view: false, create: false, update: false, delete: false },
      inventory: { view: true, create: false, update: false, delete: false },
      bookings: { view: true, create: false, update: true, delete: false },
      customers: { view: true, create: false, update: false, delete: false },
      payments: { view: false, create: false, update: false, delete: false },
      cms: { view: false, create: false, update: false, delete: false },
      users: { view: false, create: false, update: false, delete: false },
      settings: { view: false, create: false, update: false, delete: false },
    },
  },
  {
    role: 'CONTENT_MANAGER',
    description: 'Mengelola halaman profil, blog artikel, banner promo, galeri modifikasi, dan FAQ website.',
    permissions: {
      products: { view: true, create: false, update: false, delete: false },
      orders: { view: false, create: false, update: false, delete: false },
      inventory: { view: false, create: false, update: false, delete: false },
      bookings: { view: false, create: false, update: false, delete: false },
      customers: { view: false, create: false, update: false, delete: false },
      payments: { view: false, create: false, update: false, delete: false },
      cms: { view: true, create: true, update: true, delete: true },
      users: { view: false, create: false, update: false, delete: false },
      settings: { view: false, create: false, update: false, delete: false },
    },
  },
];

// CMS Initial Data
export const initialCMSPages: CMSPage[] = [
  {
    id: 'page-home',
    title: 'Beranda / Homepage',
    slug: 'home',
    content: 'Hero section bengkel, katalog produk unggulan, layanan booking online, testimoni, dan lokasi.',
    metaTitle: 'JTM Tech - Bengkel Spesialis Matic & Toko Racing Part Terpercaya',
    metaDescription: 'Layanan service motor matic, dyno tuning, upgrade CVT, dan suku cadang original bergaransi di Malang.',
    status: 'PUBLISHED',
    updatedAt: '2026-08-20',
  },
  {
    id: 'page-about',
    title: 'Tentang Kami & Profil Bengkel',
    slug: 'about-us',
    content: 'Didirikan sejak tahun 2018, JTM Tech melayani ribuan motor dengan mekanik tersertifikasi dan peralatan canggih.',
    metaTitle: 'Tentang Bengkel JTM Tech - Pengalaman & Fasilitas Bengkel',
    metaDescription: 'Kenali sejarah, fasilitas mesin dyno, mekanik handal, dan visi misi JTM Tech dalam otomotif roda dua.',
    status: 'PUBLISHED',
    updatedAt: '2026-08-15',
  },
  {
    id: 'page-services',
    title: 'Daftar Layanan & Paket Service',
    slug: 'services',
    content: 'Daftar lengkap paket service CVT, gurah mesin injeksi, overhaul total, dan dyno tuning.',
    metaTitle: 'Paket Service Motor & Biaya Perawatan - JTM Tech',
    metaDescription: 'Cek daftar harga service motor berkala, servis CVT, pembersihan injektor, dan bore up motor.',
    status: 'PUBLISHED',
    updatedAt: '2026-08-18',
  },
];

export const initialArticles: Article[] = [
  {
    id: 'art-001',
    title: 'Penyebab Motor Matic Gredek Saat Tarikan Awal & Cara Ampuh Mengatasinya',
    slug: 'penyebab-motor-matic-gredek-tarikan-awal',
    category: 'Tips Perawatan Motor',
    thumbnail: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=500&auto=format&fit=crop&q=80',
    excerpt: 'Kenali faktor debu pada mangkok ganda, kampas ganda aus, atau roller peyang yang menyebabkan getaran tidak nyaman.',
    content: 'Gejala motor matic bergetar hebat atau "gredek" di kecepatan rendah sering dikeluhkan pemilik Honda Vario, Beat, hingga NMAX...',
    author: 'Agus Bogel (Head Mechanic)',
    views: 1420,
    status: 'PUBLISHED',
    publishedAt: '2026-08-12',
  },
  {
    id: 'art-002',
    title: 'Panduan Memilih Bobot Gram Roller CVT Sesuai Kebutuhan Harian vs Touring',
    slug: 'panduan-memilih-roller-cvt-harian-touring',
    category: 'Modifikasi & Performa',
    thumbnail: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    excerpt: 'Roller enteng untuk akselerasi stop-and-go perkotaan, atau roller berat untuk top speed trek lurus panjang.',
    content: 'Karakter tenaga motor matic sangat dipengaruhi oleh kombinasi berat roller pada pulley depan...',
    author: 'Ahmad Fauzi',
    views: 980,
    status: 'PUBLISHED',
    publishedAt: '2026-08-19',
  },
];

export const initialBanners: Banner[] = [
  {
    id: 'ban-001',
    title: 'PROMO MERDEKA SERVICE CVT HANYA RP 65.000',
    subtitle: 'Gratis Greasing High-Temp + Cek 15 Titik Keselamatan Motor',
    imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=1000&auto=format&fit=crop&q=80',
    linkUrl: '/booking',
    target: '_self',
    position: 'HERO_SLIDER',
    status: 'ACTIVE',
    order: 1,
  },
  {
    id: 'ban-002',
    title: 'Cashback 10% Setiap Pembelian Shockbreaker RCB & Bendix Brake',
    subtitle: 'Berlaku untuk semua pembelian online & pasang di bengkel',
    imageUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=1000&auto=format&fit=crop&q=80',
    linkUrl: '/products',
    target: '_self',
    position: 'PROMO_BAR',
    status: 'ACTIVE',
    order: 2,
  },
];

export const initialGallery: GalleryItem[] = [
  {
    id: 'gal-001',
    title: 'Overhaul Total & Porting Polish Honda Vario 160cc',
    category: 'WORKSHOP_ACTIVITY',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
    description: 'Pembersihan kerak ruang bakar dan finishing porting intake/exhaust untuk efisiensi volumetrik.',
    date: '2026-08-22',
  },
  {
    id: 'gal-002',
    title: 'Dyno Test & AFR Mapping Kawasaki ZX-25R Titanium Exhaust',
    category: 'DYNO_TUNING',
    imageUrl: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=600&auto=format&fit=crop&q=80',
    description: 'Peningkatan tenaga puncak 4.2 HP setelah kalibrasi ECU Racing.',
    date: '2026-08-23',
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: 'test-001',
    customerName: 'Rendy Kurniawan',
    vehicle: 'Yamaha Aerox 155 CyberCity',
    serviceUsed: 'Service CVT + Ganti Roller Daytona',
    rating: 5,
    comment: 'Tarikan motor jadi enteng banget dan gredek langsung hilang total. Pengerjaan rapi dan mekanik komunikatif!',
    status: 'APPROVED',
    date: '2026-08-21',
  },
  {
    id: 'test-002',
    customerName: 'Hendro Prasetyo',
    vehicle: 'Honda PCX 160',
    serviceUsed: 'Gurah Mesin Injeksi + Ganti Oli Motul',
    rating: 5,
    comment: 'Bengkel paling recommended di Malang. Ruang tunggu nyaman ber-AC dan ada live monitor CCTV mekanik.',
    status: 'APPROVED',
    date: '2026-08-23',
  },
];

export const initialFAQs: FAQ[] = [
  {
    id: 'faq-001',
    question: 'Berapa lama estimasi waktu pengerjaan Service CVT Komplit?',
    answer: 'Pengerjaan Service CVT membutuhkan waktu sekitar 35 - 45 menit tergantung kondisi kebersihan komponen.',
    category: 'SERVICE',
    order: 1,
    status: 'ACTIVE',
  },
  {
    id: 'faq-002',
    question: 'Bagaimana cara melakukan Booking Service agar tidak perlu antre?',
    answer: 'Anda dapat memilih menu Service Bookings di website ini, menentukan tanggal, jam kedatangan, dan mekanik yang diinginkan.',
    category: 'SERVICE',
    order: 2,
    status: 'ACTIVE',
  },
  {
    id: 'faq-003',
    question: 'Apakah produk sparepart yang dibeli di toko online dijamin original?',
    answer: 'Seluruh sparepart dan oli yang kami jual 100% Original bergaransi resmi dari distributor resmi (Motul, Daytona, RCB, TDR, dll).',
    category: 'ORDER',
    order: 3,
    status: 'ACTIVE',
  },
];

export const initialMedia: MediaFile[] = [
  {
    id: 'med-001',
    name: 'motul-7100-synthetic.jpg',
    url: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=500&auto=format&fit=crop&q=80',
    sizeBytes: 345000,
    mimeType: 'image/jpeg',
    dimensions: '1200x800',
    folder: 'products',
    createdAt: '2026-08-20',
  },
  {
    id: 'med-002',
    name: 'daytona-cvt-roller.jpg',
    url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    sizeBytes: 420000,
    mimeType: 'image/jpeg',
    dimensions: '1200x800',
    folder: 'products',
    createdAt: '2026-08-20',
  },
  {
    id: 'med-003',
    name: 'bca-transfer-proof-siti.jpg',
    url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=500&auto=format&fit=crop&q=80',
    sizeBytes: 280000,
    mimeType: 'image/jpeg',
    dimensions: '800x1200',
    folder: 'payments',
    createdAt: '2026-08-25',
  },
];

export const initialSettings: WorkshopSettings = {
  businessInfo: {
    name: 'JTM TECH MotoWorkshop & Store',
    tagline: 'Modern Motorcycle Workshop & Performance Sparepart Hub',
    address: 'Jl. Raya Sulfat No. 88, Purwantoro, Blimbing',
    city: 'Kota Malang',
    province: 'Jawa Timur',
    postalCode: '65122',
    phone: '0341-456789',
    whatsapp: '0812-3456-7890',
    email: 'info@jtmtech.id',
    openingHours: {
      weekdays: '08:00 - 17:00 WIB',
      saturday: '08:00 - 17:00 WIB',
      sunday: '09:00 - 15:00 WIB',
    },
    googleMapsUrl: 'https://maps.google.com/?q=JTM+Tech+Malang',
  },
  paymentSettings: {
    qrisEnabled: true,
    qrisMerchantName: 'BENGKEL JTM TECH INDONESIA',
    qrisNMID: 'ID1020261928301',
    qrisImageUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=00020101021226590014ID.LINKAJA.WWW011893600918000000010202020251440014ID.GO.QRIS.WWW0215ID10202619283010303UME5204581253033605802ID5920BENGKEL+JTM+TECH+ID6006MALANG61056512262070703A016304856E',
    bankAccounts: [
      {
        bank: 'Bank Central Asia (BCA)',
        accountNumber: '1234-5678-90',
        accountHolder: 'Bengkel JTM Tech PT',
        active: true,
      },
      {
        bank: 'Bank Mandiri',
        accountNumber: '1400-0192-8374-1',
        accountHolder: 'Bengkel JTM Tech PT',
        active: true,
      },
      {
        bank: 'Bank Rakyat Indonesia (BRI)',
        accountNumber: '0012-0100-9988-501',
        accountHolder: 'Bengkel JTM Tech PT',
        active: true,
      },
    ],
    manualVerificationInstructions: 'Silakan transfer sesuai nominal total hingga 3 digit terakhir. Unggah foto bukti transfer melalui halaman pesanan atau WhatsApp admin.',
  },
  shippingSettings: {
    allowWorkshopPickup: true,
    pickupInstructions: 'Pesanan dapat diambil langsung di kasir toko JTM Tech Malang dengan menunjukkan nomor order/invoice.',
    couriers: [
      { name: 'JNE (Reguler, YES, JTR)', code: 'JNE', active: true },
      { name: 'J&T Express (EZ, Super)', code: 'JNT', active: true },
      { name: 'SiCepat Ekspres (GOKIL, BEST)', code: 'SICEPAT', active: true },
      { name: 'GoSend / GrabExpress Instant (Malang Area)', code: 'INSTANT', active: true },
    ],
    defaultOriginCity: 'Kota Malang (65122)',
  },
  websiteSettings: {
    logoUrl: '/img/layout/logo.png',
    faviconUrl: '/favicon.ico',
    siteTitle: 'JTM TECH - Modern Workshop & Moto Parts Store',
    metaDescription: 'Sistem Manajemen Bengkel Motor Modern, Booking Servis Online, dan Toko Sparepart Racing Original Terlengkap.',
    keywords: ['bengkel motor malang', 'service cvt vario nmax', 'toko oli motul original', 'booking service bengkel', 'dyno test malang'],
    socialMedia: {
      instagram: 'https://instagram.com/jtmtech_official',
      tiktok: 'https://tiktok.com/@jtmtech_speed',
      youtube: 'https://youtube.com/@jtmtech_moto',
      facebook: 'https://facebook.com/jtmtech.workshop',
    },
  },
};
